### ISSUE TITLE
实现多条回复了吗？

### ISSUE THREAD

**Issue by adustdu2015** [kslr/WechatAutoReply#1]
我看到你在另外一个开源库上提到同时回复多条，我想问一下，你这个开源库实现了吗？或者你有没有一个具体的思路？请教一下。谢谢

**Comment by kslr** [comment]
hi @adustdu2015 
 可以做成bot形式

**Comment by adustdu2015** [comment]
bot是什么呀？

**Comment by kslr** [comment]
比如 https://github.com/littlecodersh/ItChat

**Comment by adustdu2015** [comment]
好像是用python写的吧，那辅助功能是不是无法实现呀？xposed你接触过吗？

**Comment by kslr** [comment]
已经换方案了，不再使用辅助功能；机器人等于是模拟了一个客户端来实现交互。xposed的成本太高了，部署起来很麻烦。

**Comment by adustdu2015** [comment]
好吧，你们以前也做过微信的二次开发吗？都有实现什么功能呢？

**Comment by kslr** [comment]
该有的都有了，没有的都没有。

**Comment by adustdu2015** [comment]
可以的，领导非要用xposed，实在很麻烦，于是发现了辅助功能，可是不能实现并发。这是又要回到脚本的年代了吗？

**Comment by kslr** [comment]
脚本很方便啊，随便一个环境都能跑起来，android也可以跑，如果你有办法扫码的话。

辅助功能也是可以的，但是要麻烦很多倍，比如监听回话列表而不是消息栏。

**Comment by adustdu2015** [comment]
你会使用xposed吗？

**Comment by adustdu2015** [comment]
你主要做android还是做js呀？亦或是其他方向呀？
